New log file opened at Tue Apr 05 15:53:07 CDT 2016 by 4480@MSI
Taking next connection to: 52282
New client attempting to connect on port: 52283-52282
  Address = /192.168.0.118:52282
This client on port 52283 has uuid 2d2183dc-1d51-4196-8d17-b4413a43b9db configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-2d2183dc-1d51-4196-8d17-b4413a43b9db
Taking next connection to: 52282
New client attempting to connect on port: 52284-52282
  Address = /192.168.0.118:52282
Handshake exception on socket: 52284
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 52282
New client attempting to connect on port: 52285-52282
  Address = /192.168.0.118:52282
This client on port 52285 has uuid b9a66f47-51e3-402d-8029-eee75a4bd827 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-2d2183dc-1d51-4196-8d17-b4413a43b9db, activator-b9a66f47-51e3-402d-8029-eee75a4bd827
Taking next connection to: 52282
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52282
New client attempting to connect on port: 52314-52282
  Address = /192.168.0.118:52282
Handshake exception on socket: 52314
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 52282
New client attempting to connect on port: 52315-52282
  Address = /192.168.0.118:52282
This client on port 52315 has uuid b13d5648-96ff-4e7d-b0cc-b85bece30886 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-b9a66f47-51e3-402d-8029-eee75a4bd827, play-fork-run-b13d5648-96ff-4e7d-b0cc-b85bece30886
Taking next connection to: 52282
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52282
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52282
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52282
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52282
